### ISSUE TITLE
Missing ../config.js

### ISSUE THREAD

**Issue by Tjoosten** [iRail/analytics#8]
I follow the installation instructions. But i get an error: 

```
D:\irail\analytics>node server.js
module.js:327
    throw err;
    ^

Error: Cannot find module '../config.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\irail\analytics\lib\data.js:2:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

D:\irail\analytics>node server.js

```

**Comment by Tjoosten** [comment]
My Bad
